[package]
name = "konduit-wasm"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.release]
release = false

[package.metadata.cargo-machete]
ignored = ["wasm-bindgen-futures"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
bln-sdk.workspace = true
cardano-connector-client = { workspace = true, features = ["wasm"] }
cardano-sdk = { workspace = true, features = ["wasm"] }
console_error_panic_hook.workspace = true
console_log.workspace = true
hex.workspace = true
http-client = { workspace = true, features = ["wasm"] }
konduit-data = { workspace = true, features = ["wasm"] }
konduit-tx.workspace = true
log.workspace = true
serde.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
web-time.workspace = true

[dev-dependencies]
serde_json.workspace = true
