[package]
name = "konduit-wasm"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.release]
release = false

[dependencies]
anyhow.workspace = true
cardano-tx-builder = { workspace = true, features = ["wasm"] }
cardano-connect = { workspace = true }
konduit-data.workspace = true
konduit-tx.workspace = true
wasm-bindgen.workspace = true
serde.workspace = true
ehttp = { version = "0.5.0", features = ["json"] }
wasm-bindgen-futures = "0.4.55"
futures.workspace = true
console_log = "1.0.0"
console_error_panic_hook = "0.1.7"
log = "0.4.28"
gloo-net = "0.6.0"
hex.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]


[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.16", features = ["js"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
