[package]
name = "konduit-wasm"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.release]
release = false

[dependencies]
anyhow.workspace = true
cardano-tx-builder = { workspace = true, features = ["wasm"] }
konduit-data.workspace = true
wasm-bindgen.workspace = true
serde.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]


[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.16", features = ["js"] }
