[package]
name = "konduit-wasm"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.release]
release = false

[dependencies]
anyhow.workspace = true
cardano-connect-wasm.workspace = true
cardano-connect.workspace = true
cardano-tx-builder = { workspace = true, features = ["wasm"] }
console_error_panic_hook.workspace = true
console_log.workspace = true
futures.workspace = true
gloo-net.workspace = true
hex.workspace = true
konduit-data.workspace = true
konduit-tx.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["js"] }
