[package]
name = "konduit-wasm"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.release]
release = false

[package.metadata.cargo-machete]
ignored = ["wasm-bindgen-futures"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
cardano-connect-wasm.workspace = true
cardano-connect = { workspace = true, features = ["wasm"] }
cardano-tx-builder = { workspace = true, features = ["wasm"] }
console_error_panic_hook.workspace = true
console_log.workspace = true
konduit-data.workspace = true
konduit-tx.workspace = true
log.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
