app = 'konduit-server'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  FX_BINANCE = 'true'
  FX_EVERY = '60s'
  KONDUIT_DB_PATH = '/var/konduit-server/db'
  KONDUIT_SERVER_HOST = '0.0.0.0'
  LND_BASE_URL = '<insert LND_BASE_URL>'
  # Secrets can be declared and pushed using 'fly secrets set' and `fly secrets deploy'.
  # For example:
  #
  # > fly secrets set KONDUIT_SIGNING_KEY=...
  # > fly secrets set KONDUIT_BLOCKFROST_PROJECT_ID=...
  # > fly secrets deploy

[[mounts]]
  source = 'db'
  destination = '/var/konduit-server'

[http_service]
  internal_port = 4444
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpus = 2
  memory = '512mb'
  memory_mb = 512
