[package]
name = "fx-client"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[[bin]]
name = "fx-print"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = [
  "dep:clap",
  "dep:dotenvy",
  "dep:humantime",
  "dep:tokio",
]
namespaced = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
# -F cli
clap = { workspace = true, features = ["derive", "env"], optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
dotenvy = { workspace = true, optional = true }
humantime = { workspace = true, optional = true }
