[package]
name = "konduit-client"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[[bin]]
name = "konduit-client"
path = "src/main.rs"
doc = false
required-features = ["cli"]

[features]
default = []
reqwest = [
  "http-client/reqwest",
  "dep:reqwest",
]
wasm = [
  "http-client/wasm",
  "konduit-data/wasm",
  "dep:wasm-bindgen",
  "dep:wasm-bindgen-futures",
]
cli = [
  "reqwest",
  "dep:bln-client",
  "dep:clap",
  "dep:dotenvy",
  "dep:tokio",
]

[dependencies]
anyhow.workspace = true
bln-sdk.workspace = true
cardano-sdk.workspace = true
hex = { workspace = true, features = ["serde"] }
http-client.workspace = true
konduit-data.workspace = true
serde.workspace = true
serde_json.workspace = true
# -F reqwest
reqwest = { workspace = true, features = ["json"], optional = true }
# -F wasm
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
# -F cli
bln-client = { workspace = true, features = ["cli", "namespaced"], optional = true }
clap = { workspace = true, features = ["env"], optional = true }
dotenvy = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
proptest.workspace = true
proptest-derive.workspace = true
