[package]
name = "http-client-wasm"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
gloo-net.workspace = true
gloo-timers.workspace = true
http-client.workspace = true
js-sys.workspace = true
log.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
web-sys.workspace = true
web-time.workspace = true
