name: Pack the WASM components

on:
  push:
    branch: [main]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build metadata
        id: meta
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            VERSION="nightly-$(git rev-parse --short=8 HEAD)"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt-get -y install binaryen
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack

      - name: Build wasm
        id: wasm
        working-directory: rust
        env:
          OUT: konduit-wasm-${{ steps.meta.outputs.version }}
        run: |
          wasm-pack build --release --target web -d $OUT crates/konduit-wasm
          echo "name=$OUT" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.wasm.outputs.name }}
          path: rust/crates/konduit-wasm/${{ steps.wasm.outputs.name }}
